function text = mt_generate_applescript(email, subject, body, attachment, mt_settings)

attachment = strcat(mt_settings.drive_name, strrep(attachment, '/', ':')); % TODO: implement for Windows

text = "set theAccount to """ + mt_settings.sender_email + '"' + newline + ...
'set theRecipient to "' + email + '"' + newline + ...
'set theAttachment to "'+ attachment +'"' + newline + ...
'set theSubject to "'+subject+'"' + newline + ...
'set theBody to "'+body+'"' + newline + ...
'set isEmailVisible to ' + mt_settings.email_appears_in_mac_mail + newline + ...
'set sendEmailAutomatically to ' + mt_settings.send_email_automatically + newline + ...
'tell application "Mail"' + newline + ...
'	set theMessage to make new outgoing message with properties {visible:isEmailVisible, subject:theSubject, content:theBody, sender:theAccount}' + newline + ...
'	tell theMessage' + newline + ...
'		make new to recipient at end of to recipients with properties {address:theRecipient}' + newline + ...
'	end tell' + newline + ...
'	tell content of theMessage' + newline + ...
'		make new attachment with properties {file name:theAttachment as alias} at after last paragraph' + newline + ...
'	end tell' + newline + ...
'	if sendEmailAutomatically then' + newline + ...
'		delay 5 # Wait for the attachment to load' + newline + ...
'		send theMessage' + newline + ...
'	end if' + newline + ...
'end tell';
